---
- name: Roll back vff-fiscal service manually
  hosts: vff_fiscal
  serial: 1
  gather_facts: true
  tasks:
    - name: Roll back service with deployment lock
      block:
        - name: Acquire deployment lock
          ansible.builtin.include_role:
            name: vff_fiscal_common
            tasks_from: acquire_deploy_lock.yml
          vars:
            vff_fiscal_common_deploy_lock_operation: rollback-service

        - name: Roll back service
          ansible.builtin.include_role:
            name: vff_fiscal_service_rollback

      always:
        - name: Release deployment lock
          ansible.builtin.include_role:
            name: vff_fiscal_common
            tasks_from: release_deploy_lock.yml
